import supabase from './db-client.js';
const cors=res=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, PUT, DELETE, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-Visitor-Id, Authorization');};
async function identity(req){const token=req.headers.authorization?.replace('Bearer ','');if(token){const{data:{user}}=await supabase.auth.getUser(token);if(user)return `user:${user.id}`;}return String(req.headers['x-visitor-id']||req.body?.visitor_id||'').slice(0,100);}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();try{const owner=await identity(req);if(!owner)return res.status(400).json({error:'معرّف الجلسة مطلوب'});
 if(req.method==='GET'){if(req.query.id){const{data:c}=await supabase.from('conversations').select('*').eq('id',req.query.id).eq('user_id',owner).maybeSingle();if(!c)return res.status(404).json({error:'المحادثة غير موجودة'});const{data,error}=await supabase.from('messages').select('id,role,content,created_at').eq('conversation_id',c.id).order('created_at',{ascending:true});if(error)throw error;return res.status(200).json({conversation:c,messages:data});}const{data,error}=await supabase.from('conversations').select('id,title,server_id,updated_at').eq('user_id',owner).order('updated_at',{ascending:false}).limit(100);if(error)throw error;return res.status(200).json(data);}
 if(req.method==='POST'){if(req.body?.action==='claim'){const token=req.headers.authorization?.replace('Bearer ','');if(!token)return res.status(401).json({error:'سجّل الدخول أولاً'});const{data:{user}}=await supabase.auth.getUser(token);if(!user)return res.status(401).json({error:'الجلسة غير صالحة'});const guest=String(req.body.guest_id||'').slice(0,100);if(guest&&guest!==`user:${user.id}`){const{error}=await supabase.from('conversations').update({user_id:`user:${user.id}`}).eq('user_id',guest);if(error)throw error;}return res.status(200).json({ok:true});}
  let{server_id}=req.body||{};if(!server_id){const{data:available}=await supabase.from('ai_servers').select('id').eq('is_active',true).order('id').limit(1).maybeSingle();server_id=available?.id;}if(!server_id)return res.status(400).json({error:'لا يوجد خادم نشط حالياً'});const{data,error}=await supabase.from('conversations').insert({user_id:owner,server_id,title:'محادثة جديدة'}).select().single();if(error)throw error;return res.status(201).json(data);}
 if(req.method==='PUT'){const{id,title}=req.body||{};if(!id||!title?.trim())return res.status(400).json({error:'العنوان مطلوب'});const{data,error}=await supabase.from('conversations').update({title:title.trim().slice(0,100),updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',owner).select().single();if(error)throw error;return res.status(200).json(data);}
 if(req.method==='DELETE'){const{id}=req.body||{};const{data:c}=await supabase.from('conversations').select('id').eq('id',id).eq('user_id',owner).maybeSingle();if(!c)return res.status(404).json({error:'المحادثة غير موجودة'});await supabase.from('messages').delete().eq('conversation_id',id);const{error}=await supabase.from('conversations').delete().eq('id',id).eq('user_id',owner);if(error)throw error;return res.status(200).json({ok:true});}return res.status(405).json({error:'الطريقة غير مدعومة'});
}catch(err){console.error('Conversations API:',err);return res.status(500).json({error:err.message||'خطأ في الخادم'});}}
