import supabase from './db-client.js';
const ADMIN_PASSWORD='12345678rk';
const cors=(res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, PUT, DELETE, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-Admin-Password');};
const mask=v=>v.length<9?'••••••••':`${v.slice(0,4)}••••${v.slice(-4)}`;
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.headers['x-admin-password']!==ADMIN_PASSWORD)return res.status(401).json({error:'كلمة مرور يوسف غير صحيحة'});try{const serverId=req.method==='GET'?req.query.server_id:req.body?.server_id;if(!serverId)return res.status(400).json({error:'الخادم مطلوب'});
 if(req.method==='GET'){const{data,error}=await supabase.from('api_keys').select('id,key_value,is_active,use_count,fail_count,last_error,last_used_at,created_at').eq('server_id',serverId).order('id',{ascending:true}).limit(5000);if(error)throw error;return res.status(200).json(data.map(({key_value,...row})=>({...row,masked_key:mask(key_value)})));}
 if(req.method==='POST'){const keys=Array.isArray(req.body?.keys)?req.body.keys:[];const unique=[...new Set(keys.map(k=>String(k).trim()).filter(Boolean))];if(!unique.length)return res.status(400).json({error:'أدخل مفتاحاً واحداً على الأقل'});if(unique.length>5000)return res.status(400).json({error:'الحد الأقصى 5000 مفتاح في الدفعة'});const{data,error}=await supabase.from('api_keys').insert(unique.map((key_value,priority)=>({server_id:serverId,key_value,is_active:true,priority}))).select('id');if(error)throw error;return res.status(201).json({added:data.length});}
 if(req.method==='PUT'){const{id,is_active}=req.body||{};const{data,error}=await supabase.from('api_keys').update({is_active:Boolean(is_active)}).eq('id',id).eq('server_id',serverId).select('id,is_active').single();if(error)throw error;return res.status(200).json(data);}
 if(req.method==='DELETE'){const{id}=req.body||{};const{error}=await supabase.from('api_keys').delete().eq('server_id',serverId).eq('id',id);if(error)throw error;return res.status(200).json({ok:true});}return res.status(405).json({error:'الطريقة غير مدعومة'});
}catch(err){console.error('Keys API:',err);return res.status(500).json({error:err.message||'خطأ في الخادم'});}}
