import supabase from './db-client.js';
const ADMIN_PASSWORD = '12345678rk';
const cors=(res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, PUT, DELETE, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-Admin-Password');};
const admin=(req)=>req.headers['x-admin-password']===ADMIN_PASSWORD;
function validEndpoint(value){try{const url=new URL(value);const host=url.hostname.toLowerCase();return url.protocol==='https:'&&!['localhost','127.0.0.1','0.0.0.0','::1'].includes(host)&&!host.endsWith('.local');}catch{return false;}}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();try{
 if(req.method==='GET'){
  const isAdmin=admin(req);let query=supabase.from('ai_servers').select('id,name,base_url,model,is_active,created_at').order('created_at',{ascending:true});if(!isAdmin)query=query.eq('is_active',true);const[{data,error},{data:positions,error:positionError}]=await Promise.all([query,supabase.from('server_positions').select('server_id,position')]);if(error)throw error;if(positionError)throw positionError;const positionMap=new Map((positions||[]).map(x=>[x.server_id,x.position]));data.sort((a,b)=>(positionMap.get(a.id)??999999)-(positionMap.get(b.id)??999999));const ids=data.map(x=>x.id);let counts={};if(ids.length){const{data:keys,error:keyError}=await supabase.from('api_keys').select('server_id,is_active').in('server_id',ids);if(keyError)throw keyError;counts=keys.reduce((a,k)=>{a[k.server_id]||={total:0,active:0};a[k.server_id].total++;if(k.is_active)a[k.server_id].active++;return a;},{});}return res.status(200).json(data.map((x,index)=>({...x,position:index+1,key_count:counts[x.id]?.total||0,active_key_count:counts[x.id]?.active||0})));
 }
 if(!admin(req))return res.status(401).json({error:'كلمة مرور يوسف غير صحيحة'});
 if(req.method==='POST'){const{name,base_url,model}=req.body||{};if(!name?.trim()||!model?.trim()||!validEndpoint(base_url))return res.status(400).json({error:'أدخل اسماً ونموذجاً ورابط HTTPS عاماً صالحاً'});const{data,error}=await supabase.from('ai_servers').insert({user_id:'public-admin',name:name.trim(),base_url:base_url.trim().replace(/\/$/,''),model:model.trim(),is_active:true}).select().single();if(error)throw error;return res.status(201).json(data);}
 if(req.method==='PUT'){const{id,name,base_url,model,is_active}=req.body||{};if(!id)return res.status(400).json({error:'معرّف الخادم مطلوب'});const patch={};if(name?.trim())patch.name=name.trim();if(model?.trim())patch.model=model.trim();if(typeof base_url==='string'){if(!validEndpoint(base_url))return res.status(400).json({error:'الرابط يجب أن يكون HTTPS عاماً'});patch.base_url=base_url.trim().replace(/\/$/,'');}if(typeof is_active==='boolean')patch.is_active=is_active;const{data,error}=await supabase.from('ai_servers').update(patch).eq('id',id).select().single();if(error)throw error;return res.status(200).json(data);}
 if(req.method==='DELETE'){const{id}=req.body||{};const{data:cs}=await supabase.from('conversations').select('id').eq('server_id',id);const cids=(cs||[]).map(x=>x.id);if(cids.length)await supabase.from('messages').delete().in('conversation_id',cids);await supabase.from('conversations').delete().eq('server_id',id);await supabase.from('api_keys').delete().eq('server_id',id);const{error}=await supabase.from('ai_servers').delete().eq('id',id);if(error)throw error;return res.status(200).json({ok:true});}
 return res.status(405).json({error:'الطريقة غير مدعومة'});
}catch(err){console.error('Servers API:',err);return res.status(500).json({error:err.message||'خطأ في الخادم'});}}
